CrudNET8MVC/Controllers/InicioController.cs
using System.Diagnostics;
using CrudNET8MVC.Data;
using Microsoft.AspNetCore.Mvc;
using CrudNET8MVC.Models;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using MimeKit;

namespace CrudNET8MVC.Controllers;

public class InicioController : Controller
{
    private readonly ApplicationDbContext _contexto;
    
    public InicioController(ApplicationDbContext contexto)
    {
        _contexto = contexto;
    }

    [HttpGet]
    public async Task <IActionResult> Index()
    {
        return View(await _contexto.Contacto.ToListAsync());
    }
    
    [Authorize]
    [HttpGet]
    public IActionResult Crear()
    {
        return View();
    }
    
    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Crear(Contacto contacto)
    {
        if (!ModelState.IsValid) return View();
        _contexto.Contacto.Add(contacto);
        await _contexto.SaveChangesAsync();
        
        // Para envio de correo
        var mensaje = new MimeMessage();
        mensaje.From.Add(new MailboxAddress("Test envio email", "antonio.hs6991@gmail.com"));
        mensaje.To.Add(new MailboxAddress("Test enviado", "klee.collage@gmail.com"));
        mensaje.Subject = "Test email asp.net core";
        mensaje.Body = new TextPart("plain")
        {
            Text = "Hola saludos desde asp.net core"
        };
        using (var cliente = new SmtpClient())
        {
            cliente.Connect("smtp.gmail.com", 587); // para gmail el puerto puede ser 465 o 587
            cliente.Authenticate("antonio.hs6991@gmail.com", "qsfl xzsj zihm lqmp");
            cliente.Send(mensaje);
            cliente.Disconnect(true);
        }
        
        
        return RedirectToAction(nameof(Index));
    }
    
    [Authorize]
    [HttpGet]
    public IActionResult Editar(int? id)
    {
        if (id == null) return NotFound();
        
        var contacto = _contexto.Contacto.Find(id);
        if (contacto == null) return NotFound();
        
        return View(contacto);
    }
    
    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Editar(Contacto contacto)
    {
        if (!ModelState.IsValid) return View();
        _contexto.Update(contacto);
        await _contexto.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public IActionResult Detalle(int? id)
    {
        if (id == null) return NotFound();
        
        var contacto = _contexto.Contacto.Find(id);
        if (contacto == null) return NotFound();
        
        return View(contacto);
    }
    public IActionResult Privacy()
    {
        return View();
    }

    [Authorize]
    [HttpGet]
    public IActionResult Borrar(int? id)
    {
        if (id == null) return NotFound();
        
        var contacto = _contexto.Contacto.Find(id);
        if (contacto == null) return NotFound();
        
        return View(contacto);
    }
    
    [HttpPost, ActionName("Borrar")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> BorrarContacto(int? id)
    {
        var contacto = await _contexto.Contacto.FindAsync(id);
        if (contacto == null) return View();
        /*Borrado*/
        _contexto.Contacto.Remove(contacto);
        await _contexto.SaveChangesAsync();
        
        return RedirectToAction(nameof(Index));
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CrudNET8MVC/Views/Inicio/Borrar.cshtml
@model CrudNET8MVC.Models.Contacto
@{
ViewData["Title"] = "Editar Contacto";
}

<div class="card card-primary">
    <div class="card-header">
        <h1 class="card-title">Borrar Contacto</h1>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-action="Borrar" method="post">
        @*ID del usuario como campo oculto*@
        <input type="hidden" asp-for="Id"/>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input asp-for="Nombre" class="form-control" readonly />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Telefono" class="control-label"></label>
            <input asp-for="Telefono" class="form-control" readonly />
            <span asp-validation-for="Telefono" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Celular" class="control-label"></label>
            <input asp-for="Celular" class="form-control" readonly />
            <span asp-validation-for="Celular" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" readonly />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-danger d-block mx-auto">
                <i class="bi bi-eraser-fill"></i>Borrar Usuario
            </button>
        </div>
    </form>
    <br />
    <div>
        <a asp-controller="Inicio" asp-action="Index">Volver</a>
    </div>
</div>

CrudNET8MVC/Views/Inicio/Crear.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model CrudNET8MVC.Models.Contacto
@{
    ViewData["Title"] = "Crear Nuevo Contacto";
}

<div class="card card-primary">
    <div class="card-header">
        <h1 class="card-title">Crear Contacto</h1>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-action="Crear" method="post">
        <div class="card-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" placeholder="Ingresa el telefono" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" placeholder="Ingresa el celular" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" placeholder="Ingresa el email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-success d-block mx-auto">
                <i class="bi bi-person-fill"></i>Crear Usuario
            </button>
        </div>
    </form>
    <br />
    <div>
        <a asp-controller="Inicio" asp-action="Index">Volver</a>
    </div>
</div>

CrudNET8MVC/Views/Inicio/Detalle.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model CrudNET8MVC.Models.Contacto
@{
    ViewData["Title"] = "Detalle del Contacto";
}

<div class="card card-primary">
    <div class="card-header">
        <h1 class="card-title">Detalle Contacto</h1>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <div class="card-body">
        <ul class="list-group">
            <li class="list-group-item"><strong>Nombre: </strong>@Html.DisplayFor(m => m.Nombre)</li>
            <li class="list-group-item"><strong>Telefono: </strong>@Html.DisplayFor(m => m.Telefono)</li>
            <li class="list-group-item"><strong>Celular: </strong>@Html.DisplayFor(m => m.Celular)</li>
            <li class="list-group-item"><strong>Email: </strong>@Html.DisplayFor(m => m.Email)</li>
        </ul>
    </div>
    <!-- /.card-body -->
    <br />
    <div>
        <a asp-controller="Inicio" asp-action="Index">Volver</a>
    </div>
</div>

CrudNET8MVC/Views/Inicio/Editar.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model CrudNET8MVC.Models.Contacto
@{
    ViewData["Title"] = "Editar Contacto";
}

<div class="card card-primary">
    <div class="card-header">
        <h1 class="card-title">Editar Contacto</h1>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-action="Crear" method="post">
        @*ID del usuario como campo oculto*@
        <input type="hidden" asp-for="Id"/>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input asp-for="Nombre" class="form-control" placeholder="Ingresa el nombre" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Telefono" class="control-label"></label>
            <input asp-for="Telefono" class="form-control" placeholder="Ingresa el telefono" />
            <span asp-validation-for="Telefono" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Celular" class="control-label"></label>
            <input asp-for="Celular" class="form-control" placeholder="Ingresa el celular" />
            <span asp-validation-for="Celular" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" placeholder="Ingresa el email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary d-block mx-auto">
                <i class="bi bi-pencil-fill"></i>Actualizar Usuario
            </button>
        </div>
    </form>
    <br />
    <div>
        <a asp-controller="Inicio" asp-action="Index">Volver</a>
    </div>
</div>

CrudNET8MVC/Views/Inicio/Index.cshtml
@model IEnumerable<CrudNET8MVC.Models.Contacto>
@{
    ViewData["Title"] = "Lista de contactos";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">CRUD de Usuarios</h3>
        <div class="float-end">
            <a asp-action="Crear" asp-controller="Inicio" class="btn btn-success d-block mx-auto btn-lg">
                <i class="bi bi-file-plus-fill"></i> Nuevo Usuario
            </a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @if (Model.Count() > 0)
        {
        <table class="table table-bordered" id="tblUsuarios" style="width: 100%; border-collapse: collapse;">
            <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m.Id)</th>
                <th>@Html.DisplayNameFor(m => m.Nombre)</th>
                <th>@Html.DisplayNameFor(m => m.Telefono)</th>
                <th>@Html.DisplayNameFor(m => m.Celular)</th>
                <th>@Html.DisplayNameFor(m => m.Email)</th>
                <th>Acciones</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(m => item.Id)</td>
                <td>@Html.DisplayFor(m => item.Nombre)</td>
                <td>@Html.DisplayFor(m => item.Telefono)</td>
                <td>@Html.DisplayFor(m => item.Celular)</td>
                <td>@Html.DisplayFor(m => item.Email)</td>
                <td>
                    <a class="btn btn-warning" asp-action="Editar" asp-route-id="@item.Id">
                        <i class="bi bi-pencil-fill"></i>Editar
                    </a>
                    <a class="btn btn-secondary" asp-action="Detalle" asp-route-id="@item.Id">
                        <i class="bi bi-info-circle-fill"></i>Detalle
                    </a>
                    <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@item.Id">
                        <i class="bi bi-eraser-fill"></i>Borrar
                    </a>
                </td>
            </tr>
            }
            </tbody>
        </table>
        }
        else
        {
        <p>No hay registro</p>
        }
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

@section Scripts{
    <script>
        $(document).ready(function () {
            //Llamar a datatable
            $('#tblUsuarios').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        });        
    </script>
}